#!/usr/bin/env node
/**
 * apply.mjs - MILESTONE 2. The first step that writes.
 *
 * What it writes:  .agent/state.json  and one marked block inside README.md
 * What it does NOT do:  rename, delete, edit your .cs files, or call a model.
 *
 * Renaming submission-N.cs to optimal.cs is not a mechanical act - deciding
 * which of three submissions is the optimal one requires reading them. That
 * lands in Milestone 3, behind an explicit classification step. Until then a
 * raw submission stays exactly where NeetCode put it and is recorded as
 * awaiting classification.
 *
 *   node scripts/apply.mjs            # write
 *   node scripts/apply.mjs --dry-run  # report only, touch nothing
 */

import { readFileSync, writeFileSync, existsSync, appendFileSync } from 'node:fs';
import { fingerprint } from './lib/normalise.mjs';
import { REPO, README_PATH, STATE_PATH, loadState, saveState, scanRepo } from './lib/scan.mjs';
import { patternFor, PATTERN_ORDER } from './lib/patterns.mjs';
import { execFileSync } from 'node:child_process';
import { join } from 'node:path';

const INDEX_PATH = join(REPO, 'index.md');

/** github.com/<owner>/<repo> from the remote, so source links are not hardcoded. */
function repoWebBase() {
  try {
    const url = execFileSync('git', ['remote', 'get-url', 'origin'], { cwd: REPO, encoding: 'utf8' }).trim();
    const m = url.match(/github\.com[:/](.+?)(?:\.git)?$/);
    return m ? `https://github.com/${m[1]}/blob/main` : null;
  } catch { return null; }
}

const dryRun = process.argv.includes('--dry-run');

const START = '<!-- PIPELINE-INDEX:START -->';
const END = '<!-- PIPELINE-INDEX:END -->';

// Path segments need escaping for markdown links; the topic folder has a space
// and an ampersand in it, which is exactly the sort of thing that silently
// produces a dead link nobody notices for a month.
const linkPath = (p) => p.split('/').map(encodeURIComponent).join('/');

function buildIndex(problems) {
  const curated = problems.filter((p) => p.curatedFiles.length > 0);
  const rows = problems.map((p, i) => {
    const sols = p.curatedFiles.length
      ? p.curatedFiles.map((f) => `\`${f.replace(/\.cs$/, '')}\``).join(' · ')
      : '_uncurated_';
    const vis = p.hasVisualizer
      ? `[view](${linkPath(`${p.path}/${p.slug}-visualizer.html`)})`
      : '—';
    const raw = p.pending.length
      ? p.pending.map((s) => s.file.replace(/^submission-/, '#').replace(/\.cs$/, '')).join(', ')
      : '—';
    return `| ${i + 1} | [${p.slug}](https://neetcode.io/problems/${p.slug}) | ${sols} | ${vis} | ${raw} |`;
  });

  const pendingCount = problems.reduce((n, p) => n + p.pending.length, 0);

  return [
    START,
    '',
    '## Index',
    '',
    `_${curated.length} of ${problems.length} problems curated · ${pendingCount} raw submission(s) awaiting classification · regenerated by \`scripts/apply.mjs\`_`,
    '',
    '| # | Problem | Solutions | Visualizer | Raw |',
    '|---|---------|-----------|------------|-----|',
    ...rows,
    '',
    END,
  ].join('\n');
}

function writeIndex(block) {
  const original = existsSync(README_PATH) ? readFileSync(README_PATH, 'utf8') : '';
  const eol = original.includes('\r\n') ? '\r\n' : '\n';
  const body = block.split('\n').join(eol);

  let next;
  if (original.includes(START) && original.includes(END)) {
    const head = original.slice(0, original.indexOf(START));
    const tail = original.slice(original.indexOf(END) + END.length);
    next = head + body + tail;
  } else {
    // First run: append. Never clobber NeetCode's own README prose.
    next = original.replace(/\s*$/, '') + eol + eol + '---' + eol + eol + body + eol;
  }

  if (next === original) return false;
  if (!dryRun) writeFileSync(README_PATH, next, 'utf8');
  return true;
}

/**
 * index.md - the GitHub Pages home page.
 *
 * Pages serves index.md in preference to README.md, so this becomes the landing
 * page for the published site while README stays the repo's front page.
 *
 * Visualizer links are RELATIVE, because Pages serves those .html files itself.
 * Source links are absolute github.com URLs, because Pages would hand a browser
 * a .cs file as plain text or a download rather than GitHub's syntax view.
 */
function buildIndexPage(problems, state) {
  const web = repoWebBase();
  const byPattern = new Map();
  for (const p of problems) {
    const k = patternFor(p.slug);
    if (!byPattern.has(k)) byPattern.set(k, []);
    byPattern.get(k).push(p);
  }

  const nice = (slug) => slug.replace(/-/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
  const out = [
    '# NeetCode Solutions',
    '',
    `${problems.length} problems · every solution carries its complexity, a study block, and a step-through visualizer.`,
    '',
    'Click a problem to watch the algorithm run. Source links open on GitHub.',
    '',
  ];

  const sections = PATTERN_ORDER.filter((k) => byPattern.has(k));
  // Any pattern not in PATTERN_ORDER would vanish silently; surface it instead.
  for (const k of byPattern.keys()) if (!sections.includes(k)) sections.push(k);

  for (const k of sections) {
    const rows = byPattern.get(k).sort((a, b) => a.slug.localeCompare(b.slug));
    out.push(`## ${k}`, '', '| Problem | Complexity | Solutions | Watch |', '|---|---|---|---|');

    for (const p of rows) {
      const cls = state.problems[p.slug]?.classification ?? {};
      const best = cls['optimal.cs'];
      const complexity = best ? `\`${best.time}\` / \`${best.space}\`` : '—';
      const sources = p.curatedFiles.length && web
        ? p.curatedFiles.map((f) => `[${f.replace(/\.cs$/, '')}](${web}/${linkPath(`${p.path}/${f}`)})`).join(' · ')
        : p.curatedFiles.map((f) => f.replace(/\.cs$/, '')).join(' · ') || '—';
      const watch = p.hasVisualizer
        ? `[▶ run](${linkPath(`${p.path}/${p.slug}-visualizer.html`)})`
        : '—';
      out.push(`| [${nice(p.slug)}](https://neetcode.io/problems/${p.slug}) | ${complexity} | ${sources} | ${watch} |`);
    }
    out.push('');
  }

  out.push('---', '', '_Generated by `scripts/apply.mjs`. Edit the grouping in `scripts/lib/patterns.mjs`._', '');
  return out.join('\n');
}

function writeIndexPage(text) {
  const prev = existsSync(INDEX_PATH) ? readFileSync(INDEX_PATH, 'utf8') : null;
  const eol = prev && prev.includes('\r\n') ? '\r\n' : '\n';
  const next = text.split('\n').join(eol);
  if (prev === next) return false;
  if (!dryRun) writeFileSync(INDEX_PATH, next, 'utf8');
  return true;
}

// ---------------------------------------------------------------- run

const state = loadState();
const problems = scanRepo(state);

for (const p of problems) {
  const rec = state.problems[p.slug] ?? {};

  // A fingerprint history, not a snapshot: if you improve optimal.cs later, a
  // resubmission of the version you replaced should still read as "seen before".
  const known = { ...(rec.knownFingerprints ?? {}), ...p.curatedPrints };

  // Spread the existing record first. Replacing it wholesale silently drops any
  // key this file does not know about - which is exactly what happened to the
  // headerSignatures that classify.mjs writes one step earlier in the workflow,
  // quietly re-enabling the nightly header churn it exists to prevent.
  state.problems[p.slug] = {
    ...rec,
    topic: p.topic,
    curatedFiles: p.curatedFiles,
    hasVisualizer: p.hasVisualizer,
    processedSubmissions: (rec.processedSubmissions ?? []).slice().sort(),
    awaitingClassification: p.pending.map((s) => s.file),
    knownFingerprints: known,
    // Kept under the key detect/scan reads, so the two never drift.
    fingerprints: known,
  };
}

// updatedAt is set by saveState, and only when something actually changed.

const indexChanged = writeIndex(buildIndex(problems));
const pageChanged = writeIndexPage(buildIndexPage(problems, state));
const stateChanged = dryRun ? true : saveState(state);
const changed = indexChanged || pageChanged || stateChanged;

const awaiting = problems.filter((p) => p.pending.length);
console.log(`\n${dryRun ? '[dry run] ' : ''}apply over ${REPO}`);
console.log(`  problems indexed        ${problems.length}`);
console.log(`  curated                 ${problems.filter((p) => p.curatedFiles.length).length}`);
console.log(`  awaiting classification ${awaiting.reduce((n, p) => n + p.pending.length, 0)} file(s) in ${awaiting.length} folder(s)`);
for (const p of awaiting) console.log(`      ${p.path}: ${p.pending.map((s) => s.file).join(', ')}`);
console.log(`  README index            ${indexChanged ? 'updated' : 'unchanged'}`);
console.log(`  ${STATE_PATH.replace(REPO + '/', '')}       ${stateChanged ? 'updated' : 'unchanged'}`);
console.log(`  => ${changed ? 'CHANGES TO COMMIT' : 'nothing to commit'}\n`);

if (process.env.GITHUB_OUTPUT) {
  appendFileSync(process.env.GITHUB_OUTPUT, `changed=${changed}\n`);
}
