#!/usr/bin/env node
/**
 * apply.mjs - MILESTONE 2. The first step that writes.
 *
 * What it writes:  .agent/state.json  and one marked block inside README.md
 * What it does NOT do:  rename, delete, edit your .cs files, or call a model.
 *
 * Renaming submission-N.cs to optimal.cs is not a mechanical act - deciding
 * which of three submissions is the optimal one requires reading them. That
 * lands in Milestone 3, behind an explicit classification step. Until then a
 * raw submission stays exactly where NeetCode put it and is recorded as
 * awaiting classification.
 *
 *   node scripts/apply.mjs            # write
 *   node scripts/apply.mjs --dry-run  # report only, touch nothing
 */

import { readFileSync, writeFileSync, existsSync, appendFileSync } from 'node:fs';
import { fingerprint } from './lib/normalise.mjs';
import { REPO, README_PATH, STATE_PATH, loadState, saveState, scanRepo } from './lib/scan.mjs';

const dryRun = process.argv.includes('--dry-run');

const START = '<!-- PIPELINE-INDEX:START -->';
const END = '<!-- PIPELINE-INDEX:END -->';

// Path segments need escaping for markdown links; the topic folder has a space
// and an ampersand in it, which is exactly the sort of thing that silently
// produces a dead link nobody notices for a month.
const linkPath = (p) => p.split('/').map(encodeURIComponent).join('/');

function buildIndex(problems) {
  const curated = problems.filter((p) => p.curatedFiles.length > 0);
  const rows = problems.map((p, i) => {
    const sols = p.curatedFiles.length
      ? p.curatedFiles.map((f) => `\`${f.replace(/\.cs$/, '')}\``).join(' · ')
      : '_uncurated_';
    const vis = p.hasVisualizer
      ? `[view](${linkPath(`${p.path}/visualizer.html`)})`
      : '—';
    const raw = p.pending.length
      ? p.pending.map((s) => s.file.replace(/^submission-/, '#').replace(/\.cs$/, '')).join(', ')
      : '—';
    return `| ${i + 1} | [${p.slug}](https://neetcode.io/problems/${p.slug}) | ${sols} | ${vis} | ${raw} |`;
  });

  const pendingCount = problems.reduce((n, p) => n + p.pending.length, 0);

  return [
    START,
    '',
    '## Index',
    '',
    `_${curated.length} of ${problems.length} problems curated · ${pendingCount} raw submission(s) awaiting classification · regenerated by \`scripts/apply.mjs\`_`,
    '',
    '| # | Problem | Solutions | Visualizer | Raw |',
    '|---|---------|-----------|------------|-----|',
    ...rows,
    '',
    END,
  ].join('\n');
}

function writeIndex(block) {
  const original = existsSync(README_PATH) ? readFileSync(README_PATH, 'utf8') : '';
  const eol = original.includes('\r\n') ? '\r\n' : '\n';
  const body = block.split('\n').join(eol);

  let next;
  if (original.includes(START) && original.includes(END)) {
    const head = original.slice(0, original.indexOf(START));
    const tail = original.slice(original.indexOf(END) + END.length);
    next = head + body + tail;
  } else {
    // First run: append. Never clobber NeetCode's own README prose.
    next = original.replace(/\s*$/, '') + eol + eol + '---' + eol + eol + body + eol;
  }

  if (next === original) return false;
  if (!dryRun) writeFileSync(README_PATH, next, 'utf8');
  return true;
}

// ---------------------------------------------------------------- run

const state = loadState();
const problems = scanRepo(state);

for (const p of problems) {
  const rec = state.problems[p.slug] ?? {};

  // A fingerprint history, not a snapshot: if you improve optimal.cs later, a
  // resubmission of the version you replaced should still read as "seen before".
  const known = { ...(rec.knownFingerprints ?? {}), ...p.curatedPrints };

  // Spread the existing record first. Replacing it wholesale silently drops any
  // key this file does not know about - which is exactly what happened to the
  // headerSignatures that classify.mjs writes one step earlier in the workflow,
  // quietly re-enabling the nightly header churn it exists to prevent.
  state.problems[p.slug] = {
    ...rec,
    topic: p.topic,
    curatedFiles: p.curatedFiles,
    hasVisualizer: p.hasVisualizer,
    processedSubmissions: (rec.processedSubmissions ?? []).slice().sort(),
    awaitingClassification: p.pending.map((s) => s.file),
    knownFingerprints: known,
    // Kept under the key detect/scan reads, so the two never drift.
    fingerprints: known,
  };
}

// updatedAt is set by saveState, and only when something actually changed.

const indexChanged = writeIndex(buildIndex(problems));
const stateChanged = dryRun ? true : saveState(state);
const changed = indexChanged || stateChanged;

const awaiting = problems.filter((p) => p.pending.length);
console.log(`\n${dryRun ? '[dry run] ' : ''}apply over ${REPO}`);
console.log(`  problems indexed        ${problems.length}`);
console.log(`  curated                 ${problems.filter((p) => p.curatedFiles.length).length}`);
console.log(`  awaiting classification ${awaiting.reduce((n, p) => n + p.pending.length, 0)} file(s) in ${awaiting.length} folder(s)`);
for (const p of awaiting) console.log(`      ${p.path}: ${p.pending.map((s) => s.file).join(', ')}`);
console.log(`  README index            ${indexChanged ? 'updated' : 'unchanged'}`);
console.log(`  ${STATE_PATH.replace(REPO + '/', '')}       ${stateChanged ? 'updated' : 'unchanged'}`);
console.log(`  => ${changed ? 'CHANGES TO COMMIT' : 'nothing to commit'}\n`);

if (process.env.GITHUB_OUTPUT) {
  appendFileSync(process.env.GITHUB_OUTPUT, `changed=${changed}\n`);
}
